[package]
name = "splitwise"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["wgpu", "advanced"] }
rusqlite = "0.29"  
serde = { version = "1.0", features = ["derive"] }  
serde_json = "1.0"  
